const questions = [
  {
    id: 1,
    question:
      '{"question":"Are you given adequate instructions/demonstrations for proceeding with lab work?","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 2,
    question:
      '{"question":"Assessment of the lab work regularly by the teacher?","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 3,
    question:
      '{"question":"Availability and maintenance of adequate equipment in Laboratories","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 4,
    question:
      '{"question":"Availability and maintenance of Fan/Lights/LCDs in Class Rooms","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 5,
    question:
      '{"question":"Availability of Grievances/Suggestion Box and action taken on Grievances lodged","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 6,
    question:
      '{"question":"Availability of Reprographic(Xerox) / Printing Facility in College Campus","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 7,
    question:
      '{"question":"Canteen Facilities (with respect to availability of quality/variety of items)","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 8,
    question:
      '{"question":"Cleanliness in Class Rooms","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 9,
    question:
      '{"question":"Cleanliness in Laboratories","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 10,
    question:
      '{"question":"Did the teacher teach the subject with suitable illustrations, case studies and applications?","options":["Everytime","Usually","Sometimes","Rarely","Never"]}',
    type: "theory",
  },
  {
    id: 11,
    question:
      '{"question":"Drinking water availability in campus","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 12,
    question:
      '{"question":"Efforts taken by the faculty to connect lab work with lectures?","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 13,
    question:
      '{"question":"Explanations given to relate lab work to actual field application?","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 14,
    question:
      '{"question":"Extent of explanation given by the teacher on the concepts underlying the experiment/practical","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 15,
    question:
      '{"question":"Extent of planning and instructions given for the experiments","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 16,
    question:
      '{"question":"Extent to which the lab work stimulates you to think?","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 17,
    question:
      '{"question":"Facilities in Hostel (Hostel Students) OR Transport Facilities provided by college (Dayscholars)","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 18,
    question:
      '{"question":"Has the teacher covered relevant topics beyond the syllabus?","options":["Everytime","Usually","Sometimes","Rarely","Never"]}',
    type: "theory",
  },
  {
    id: 19,
    question:
      '{"question":"How interesting are the lab sessions?","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 20,
    question:
      '{"question":"How is the content covered in the lab Manual/lab instructions?","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 21,
    question:
      '{"question":"How much portion of the syllabus was covered by the teacher?","options":["95 to 100%","85 to 94%","75 to 84%","74 to 65%","Below 65%"]}',
    type: "theory",
  },
  {
    id: 22,
    question:
      '{"question":"How well the teacher was able to communicate with the students?","options":["Always effective","Sometimes effective","Satisfactory","Generally ineffective","Very poor communication"]}',
    type: "theory",
  },
  {
    id: 23,
    question:
      '{"question":"Infrastructure for club activities","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 24,
    question:
      '{"question":"Infrastructure for Sports activities","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 25,
    question:
      '{"question":"Internet / wifi Facility in Laboratory/Campus","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 26,
    question:
      '{"question":"Level in which the difficulties are entertained during lab session?","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 27,
    question:
      '{"question":"Level in which the experiments were covered as per the schedule?","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 28,
    question:
      '{"question":"Library Timings and the System followed in issue of books in College Library","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 29,
    question:
      '{"question":"Medical Facility in campus","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 30,
    question:
      '{"question":"Mentoring System in College","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 31,
    question:
      '{"question":"Placement Guidance & Support given by TDP cell (Placement cell)","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 32,
    question:
      '{"question":"Quality of available books in College Library","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 33,
    question:
      '{"question":"Quality of inputs provided during the entire duration of the experiment session?","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 34,
    question:
      '{"question":"Quality of Training Programs organized by TDP cell","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 35,
    question:
      '{"question":"Support by Administrative Office","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 36,
    question:
      '{"question":"Teacher’s control and command over the laboratory class?","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 37,
    question:
      '{"question":"The percentage use of ICT tools by the teacher, such as LCD projector, Multimedia, etc. while teaching was,","options":["Above 90%","70 to 89%","50 to 69%","30 to 59%","Below 29%"]}',
    type: "theory",
  },
  {
    id: 38,
    question:
      '{"question":"The syllabus content was covered unit by unit in uniform way.","options":["Strongly agree","Agree","Neutral","Disagree","Strongly disagree"]}',
    type: "theory",
  },
  {
    id: 39,
    question:
      '{"question":"The teacher identifies your strengths and encourages you with providing right level of challenges.","options":["Fully","Reasonably","Partially","Slightly","Unable to"]}',
    type: "theory",
  },
  {
    id: 40,
    question:
      '{"question":"The teacher motivates the students to ask questions and clear their doubts?","options":["Strongly agree","Agree","Neutral","Disagree","Strongly disagree"]}',
    type: "theory",
  },
  {
    id: 41,
    question:
      '{"question":"The teacher values the answer scripts, gives the marks of the cycle tests in time and discusses the answers in the classroom?","options":["Strongly agree","Agree","Neutral","Disagree","Strongly disagree"]}',
    type: "theory",
  },
  {
    id: 42,
    question:
      '{"question":"Time given to perform the experiment? (in terms of adequacy)","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
  {
    id: 43,
    question:
      '{"question":"Washroom facility within the campus (with respect to proximity and cleanliness)","options":["Excellent","Very Good","Good","Satisfactory","Not Satisfactory"]}',
    type: "infra",
  },
  {
    id: 44,
    question:
      '{"question":"Were practical demonstrations and hands-on training given for the relevant topics?","options":["Regularly","Often","Sometimes","Rarely","Never"]}',
    type: "theory",
  },
  {
    id: 45,
    question:
      '{"question":"Working condition of machinery at the time of performance?","options":["Excellent","Very Good","Good","Fair","Poor"]}',
    type: "lab",
  },
];

const masterTableData = [
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 3,
    Section: "A",
    "Sub Code": "MA2201",
    "Sub Name": "LINEAR ALGEBRA AND BOUNDARY VALUE PROBLEMS",
    Staff: "MR.P.PANDIARAJ \u2013 MATHS",
    "StaffParent Dept": "MATHS",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD3T1",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 3,
    Section: "A",
    "Sub Code": "EC2201",
    "Sub Name": "DIGITAL SYSTEM DESIGN AND MICROPROCESSORS",
    Staff: "MR.P.ARAVIND \u2013 ECE",
    "StaffParent Dept": "ECE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD3T2",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 3,
    Section: "A",
    "Sub Code": "AI2201",
    "Sub Name": " ARTIFICIAL INTELLIGENCE",
    Staff: "DR.G.NIRMALA",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD3T3",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 3,
    Section: "A",
    "Sub Code": "AI2202",
    "Sub Name": " DATA STRUCTURES AND ALGORITHMS",
    Staff: "Mrs.S.HEMASWATHI",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD3T4",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 3,
    Section: "A",
    "Sub Code": "CS2202",
    "Sub Name": " OBJECT ORIENTED PROGRAMMING USING JAVA",
    Staff: "Ms.D.PRADHIBA ",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD3T5",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 3,
    Section: "A",
    "Sub Code": "CS2203",
    "Sub Name": "SYSTEM SOFTWARE AND OPERATING SYSTEMS",
    Staff: "Mrs. INDUMATHI",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD3T6",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Lab",
    Semester: 3,
    Section: "A",
    "Sub Code": "AI2203",
    "Sub Name": "DATA STRUCTURES AND ALGORITHMS LABORATORY",
    Staff: "Mrs. S.HEMASWATHI",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD3L1",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Lab",
    Semester: 3,
    Section: "A",
    "Sub Code": "AI2203i",
    "Sub Name": "DATA STRUCTURES AND ALGORITHMS LABORATORY",
    Staff: "Mrs. X.IGNATIUS SELVARANI",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD3L1",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Lab",
    Semester: 3,
    Section: "A",
    "Sub Code": "AI2203ii",
    "Sub Name": "DATA STRUCTURES AND ALGORITHMS LABORATORY",
    Staff: "Mrs.  E.  VIJAYALAKSHMI",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD3L1",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Lab",
    Semester: 3,
    Section: "A",
    "Sub Code": "EC2202",
    "Sub Name": "DIGITAL SYSTEM DESIGN AND MICROPROCESSORS LABORATORY",
    Staff: "MR.P.ARAVIND -  ECE",
    "StaffParent Dept": "ECE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD3L2",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 5,
    Section: "A",
    "Sub Code": "AI2301",
    "Sub Name": "BIG DATA TOOLS AND TECHNIQUES",
    Staff: "Mrs. V.SANGEETHA, DR.U.KUMARAN",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD5T1",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 5,
    Section: "A",
    "Sub Code": "AI2302",
    "Sub Name": "COMPUTER NETWORKS AND SECURITY",
    Staff: "DR.G.MAHALAKSHMI, MR.D.ASIR",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD5T2",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 5,
    Section: "A",
    "Sub Code": "AI2303",
    "Sub Name": "FUNDAMENTALS OF DEEP LEARNING",
    Staff: "Mrs. R.INDHUJA",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD5T3",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 5,
    Section: "A",
    "Sub Code": "CS2301",
    "Sub Name": "INTERNET PROGRAMMING",
    Staff: "MR. G. PRAVEEN KUMAR",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD5T4",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 5,
    Section: "A",
    "Sub Code": "VCS321",
    "Sub Name": "AGILE PROJECT DEVELOPMENT WITH SCRUM",
    Staff: "Mrs. K.LEELARANI",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "PE",
    "Sub Grouping": "AD5T5",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 5,
    Section: "A",
    "Sub Code": "VCS316",
    "Sub Name": "INFORMATION RETRIEVAL TECHNIQUES",
    Staff: "Mrs. S.ATHILAKSHMI",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "PE",
    "Sub Grouping": "AD5T6",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Lab",
    Semester: 5,
    Section: "A",
    "Sub Code": "AI2304",
    "Sub Name": "DEEP LEARNING LABORATORY",
    Staff: "Mrs. R.INDHUJA, Mrs. R.HARIPRIYA",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD5L1",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Lab",
    Semester: 5,
    Section: "A",
    "Sub Code": "CS2307",
    "Sub Name": "INTERNET PROGRAMMING LABORATORY",
    Staff: "MR. G. PRAVEENKUMAR, DR.G.NIRMALA",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD5L2",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Lab",
    Semester: 5,
    Section: "A",
    "Sub Code": "EM2202",
    "Sub Name": "INTERPERSONAL SKILLS \u2013 LISTENING AND SPEAKING",
    Staff: "DR.N.SUNDARARAJAN \u2013 ENGLISH & Mrs.KAYILVIZLI",
    "StaffParent Dept": "ENGLISH",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD5L3",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 7,
    Section: "A",
    "Sub Code": "AD1701",
    "Sub Name": "DATA EXPLORATION AND VISUALIZATION",
    Staff: "Mrs. R.HARIPRIYA",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD7T1",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 7,
    Section: "A",
    "Sub Code": "AD1702",
    "Sub Name": " FUNDAMENTALS OF NATURAL LANGUAGE PROCESSING",
    Staff: "DR.R.RAMYA",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD7T2",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 7,
    Section: "A",
    "Sub Code": "CS1636",
    "Sub Name": " FULL STACK DEVELOPMENT",
    Staff: "Mrs. B.SANTHIPRIYA,",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD7T3",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 7,
    Section: "A",
    "Sub Code": "CS1732",
    "Sub Name": "SOFTWARE PROJECT MANAGEMENT",
    Staff: "Mrs. S.PRIYAA ",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "PE",
    "Sub Grouping": "AD7T4",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 7,
    Section: "A",
    "Sub Code": "CS1734",
    "Sub Name": " PRINCIPLES OF CYBER SECURITY",
    Staff: "Mrs. S.HEMASWATHI / MR. J. JOHN LIVINGSTON",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "PE",
    "Sub Grouping": "AD7T5",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 7,
    Section: "A",
    "Sub Code": "AD1733",
    "Sub Name": "ENTERPRISE APPLICATION DEVELOPMENT",
    Staff: "MR.R. KUMARAVEL",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "PE",
    "Sub Grouping": "AD7T6",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 7,
    Section: "A",
    "Sub Code": "AD1735",
    "Sub Name": " VIRTUALIZATION AND CLOUD COMPUTING",
    Staff: "MR.RAJASEKARAN",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "PE",
    "Sub Grouping": "AD7T7",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 7,
    Section: "A",
    "Sub Code": "OMA171",
    "Sub Name": "GRAPH THEORY AND ITS APPLICATIONS\u00a0",
    Staff: "DR.N.MEHALA \u2013 MATHS",
    "StaffParent Dept": "MATHS",
    "Open Elective/Regular/Core Elective": "OE",
    "Sub Grouping": "AD7T8",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 7,
    Section: "A",
    "Sub Code": "OEE173",
    "Sub Name": "ELECTRICAL SAFETY",
    Staff: "MR. T. HARI PRASATH \u2013 EEE",
    "StaffParent Dept": "EEE",
    "Open Elective/Regular/Core Elective": "OE",
    "Sub Grouping": "AD7T8",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 7,
    Section: "A",
    "Sub Code": "OME761",
    "Sub Name": "3D PRINTING AND DESIGN",
    Staff: "DR. S. SENTHIL \u2013 PRINCIPAL",
    "StaffParent Dept": "PRINCIPAL",
    "Open Elective/Regular/Core Elective": "OE",
    "Sub Grouping": "AD7T8",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Theory",
    Semester: 7,
    Section: "A",
    "Sub Code": "OME764",
    "Sub Name": "TESTING OF MATERIALS",
    Staff: "MR. P. SENTHAMARAIKANNAN \u2013 MECH",
    "StaffParent Dept": "MECH",
    "Open Elective/Regular/Core Elective": "OE",
    "Sub Grouping": "AD7T8",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Lab",
    Semester: 7,
    Section: "A",
    "Sub Code": "AD1711",
    "Sub Name": "DATA VISUALIZATION LABORATORY",
    Staff: "Mrs. R.HARIPRIYA,  Mrs. K.INDUMATHI",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD7L1",
  },
  {
    "Academic yr": "2023-24",
    Dept: "AD",
    "UG/PG": "UG",
    "Theory/Lab": "Lab",
    Semester: 7,
    Section: "A",
    "Sub Code": "AD1712",
    "Sub Name": "NATURAL LANGUAGE PROCESSING LABORATORY",
    Staff: "DR.R.RAMYA, Mrs. B.SANTHI PRIYA",
    "StaffParent Dept": "CSE",
    "Open Elective/Regular/Core Elective": "REG",
    "Sub Grouping": "AD7L2",
  },
];

const departments = [
  {
    deptid: 0,
    deptsname: "AL",
    deptname: "ALL",
    deptfullname: "COLLEGE",
  },
  {
    deptid: 1,
    deptsname: "CS",
    deptname: "CSE",
    deptfullname: "COMPUTER  SCIENCE AND ENGINEERING",
  },
  {
    deptid: 2,
    deptsname: "EE",
    deptname: "EEE",
    deptfullname: "ELECTRICAL &ELECTRONICS ENGINEERING",
  },
  {
    deptid: 3,
    deptsname: "EI",
    deptname: "EIE",
    deptfullname: "ELECTRONICS AND INSTRUMENATION ENGG",
  },
  {
    deptid: 4,
    deptsname: "CI",
    deptname: "CIV",
    deptfullname: "CIVIL ENGINEERING",
  },
  {
    deptid: 5,
    deptsname: "BT",
    deptname: "BTE",
    deptfullname: "BIOTECHNOLOGY",
  },
  {
    deptid: 6,
    deptsname: "IT",
    deptname: "IT",
    deptfullname: "INFORMATION TECHNOLOGY",
  },
  {
    deptid: 7,
    deptsname: "ME",
    deptname: "MEC",
    deptfullname: "MECHANICAL",
  },
  {
    deptid: 8,
    deptsname: "MT",
    deptname: "MTR",
    deptfullname: "MECHATRONICS",
  },
  {
    deptid: 9,
    deptsname: "EC",
    deptname: "ECE",
    deptfullname: "ELECTRONICS AND COMMUNICATION  ENGG",
  },
  {
    deptid: 10,
    deptsname: "PT",
    deptname: "PTE",
    deptfullname: "POLYMER TECHNOLOGY",
  },
  {
    deptid: 11,
    deptsname: "SS",
    deptname: "SSS",
    deptfullname: "M.Sc SOFTWARE SYSTEM",
  },
  {
    deptid: 12,
    deptsname: "PE",
    deptname: "PEE",
    deptfullname: "EEE -PG -POWERSYSTEM",
  },
  {
    deptid: 13,
    deptsname: "AD",
    deptname: "ADS",
    deptfullname: "ARTIFICIALINTELLIGENCE &DATASCIENCE",
  },
  {
    deptid: 14,
    deptsname: "PS",
    deptname: "PGS",
    deptfullname: "PG-CIVIL-STRUCTURAL ENGINEERING",
  },
  {
    deptid: 15,
    deptsname: "MB",
    deptname: "BTE",
    deptfullname: "PG BIOTECHNOLOGY",
  },
  {
    deptid: 16,
    deptsname: "PC",
    deptname: "PGC",
    deptfullname: "PG MECH CAD CAM",
  },
  {
    deptid: 17,
    deptsname: "MP",
    deptname: "MPT",
    deptfullname: "MTECH-POLYMER TECHNOLGY",
  },
  {
    deptid: 18,
    deptsname: "PN",
    deptname: "PCN",
    deptfullname: "PG-COMUNICATION & NETWORKING",
  },
  {
    deptid: 19,
    deptsname: "MC",
    deptname: "MCS",
    deptfullname: "PG-Computer  Science and Engineerin",
  },
];

module.exports = { questions, masterTableData, departments };
