export const DepartmentName = {
  AD: "Artificial Intelligence and Data Science",
  CS: "Computer Science",
  EE: "DepartmentName",
  EI: "DepartmentName",
  CI: "DepartmentName",
  BT: "DepartmentName",
  IT: "DepartmentName",
  ME: "DepartmentName",
  MT: "DepartmentName",
  EC: "DepartmentName",
  PT: "DepartmentName",
  PS: "DepartmentName",
  MB: "DepartmentName",
};
